local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: true  # 不使用静态地图，局部代价地图是动态生成的
  rolling_window: true #  启用滚动窗口模式，代价地图会随着机器人移动而移动
  width: 3
  height: 3  
  resolution: 0.05 # 代价地图分辨率为0.01米/像素！！！！！！！！！！！！可能需要更改
  transform_tolerance: 0.5  
  origin_x: 0  # 代价地图原点X坐标为0
  origin_y: 0  

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}

    