polygons:
  # - [ {x: 0.0, y: 0.0}, {x: 5.0, y: 0.0}, {x: 5.0, y: 5.0}, {x: 0.0, y: 5.0} ]
  # - [ {x: 10.0, y: 10.0}, {x: 15.0, y: 10.0}, {x: 15.0, y: 15.0}, {x: 10.0, y: 15.0} ]
  - [ {x: 0.5, y: 2.0}, {x: 0.5, y: 3.0}, {x: -0.5, y: 2}, {x: -0.5, y: 3.0} ]
